import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import React, { useCallback, useEffect, useState } from "react";
import axiosClient from "@/#@/libraries/axiosClient";
import Link from "next/link";
import HomeBanner from "@/#@/components/Banner/HomeBanner";

const inter = Inter({ subsets: ["latin"] });

function Index() {
  const [products, setProducts] = useState([]);
  // Call API

  const getProducts = useCallback(async () => {
    try {
      const res = await axiosClient.get("/products");
      console.log("res.data", res.data);
      setProducts(res.data);
    } catch (error) {
      console.log(error);
    }
  }, []);

  useEffect(() => {
    getProducts();
  }, [getProducts]);
  console.log("products", products);

  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {products && products.length > 0 ? (
        <div style={{ display: "flex", flexDirection: "column" }}>
          {products.map((p: any) => (
            <Link key={p._id} href={`/products/${p._id}`}>
              <h1>{p.name}</h1>
            </Link>
          ))}
        </div>
      ) : (
        <small>Không có sản phẩm</small>
      )}
    </>
  );
}
export default Index;
